### ISSUE TITLE
执行报错

### ISSUE THREAD

**Issue by komomon** [adnane-X-tebbaa/Katana#11]
![image](https://user-images.githubusercontent.com/52700174/97386501-e9f02c80-190e-11eb-8ecd-0d3685423433.png)
您好，每次执行一会，程序就会报错，我也没找到  .google-cookie文件。

**Comment by adnane-X-tebbaa** [comment]
您好，请检查目录（如果您按照bin / test / kds.py运行脚本），cookie文件将位于/ test目录中

**Comment by komomon** [comment]
您好，我检查了，原来也检查了，依然没发现.google-cookie文件，隐藏文件显示选项已打开，但并未发现此文件。
以下是我的截图：









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "adnane-X-tebbaa/Katana"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月5日(星期四) 凌晨1:29
收件人:&nbsp;"adnane-X-tebbaa/Katana"<Katana@noreply.github.com&gt;;
抄送:&nbsp;"栈先生"<984839993@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [adnane-X-tebbaa/Katana] 执行报错 (#11)





 
您好，请检查目录（如果您按照bin / test / kds.py运行脚本），cookie文件将位于/ test目录中
