### ISSUE TITLE
Module "Twisted" seems deprecated

### ISSUE THREAD

**Issue by ServerRaider** [adnane-X-tebbaa/Katana#13]
The module Twisted seems deprecated and won't to install.
Please check it.

**Comment by SS-Einsatzgruppe** [comment]
Run it using python3 and itll solve your issues

**Comment by adnane-X-tebbaa** [comment]
hi @ServerRaider sorry for the very very late reply as @SS-Einsatzgruppe said use python3 
Thanks!
