### ISSUE TITLE
Use proxyfile

### ISSUE THREAD

**Issue by dederaditya** [adnane-X-tebbaa/Katana#14]
Hello is it possible to make the program use a proxyfile?
It's also better to make the program saves the output from proxy scraping

**Comment by SS-Einsatzgruppe** [comment]
use proxychains bro simple requires no edit to the Script

**Comment by Arinze1020** [comment]
I have done it already on my own I perform a Pull Request but the owner don't seem to be online

**Comment by adnane-X-tebbaa** [comment]
Hi! @dederaditya 
Hi! @Arinze1020 
Katana is Acctually a 3year old python tool so it stops here
also @Arinze1020 if you can do a pull request to the New script Grecon 
Thanks!
