### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by JPoulsen0fficial** [adnane-X-tebbaa/Katana#6]
i get an error when trying to use the "-g" 
Too many requests? changing TLD doesn't work.. still throws the same error.
![too_many_requests](https://user-images.githubusercontent.com/62881413/77902241-27a9ab80-7281-11ea-9c94-c0872034fbff.png)

**Comment by adnane-X-tebbaa** [comment]
Hi **JPoulsen0fficial** try to **change the TLD** or **change your ip** or simply **use a good vpn**
Thank you
