### ISSUE TITLE
you know

### ISSUE THREAD

**Issue by enoleriand-alt** [adnane-X-tebbaa/Katana#8]
Traceback (most recent call last):
  File "Gmode.py", line 2, in <module>
    import proxybroker
ModuleNotFoundError: No module named 'proxybroker'

**Comment by enoleriand-alt** [comment]
Traceback (most recent call last):
  File "Gmode.py", line 2, in <module>
    import proxybroker
ModuleNotFoundError: No module named 'proxybroker'

**Comment by enoleriand-alt** [comment]
and I already installed it

**Comment by enoleriand-alt** [comment]
can you improve your project?

**Comment by enoleriand-alt** [comment]
and it's not just me who experienced it 🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣

**Comment by adnane-X-tebbaa** [comment]
hi @enoleriand-alt 
please use python 3.8 or 3.7  or check you environment 
 proxy mode not supported by python 3.8
 the project currently under dev  and if you have any idea you are free to open a suggestion  to improve the project 
 please  if the solution worked inform me to close the issue

**Comment by enoleriand-alt** [comment]
can you try on termux or on userland

**Comment by adnane-X-tebbaa** [comment]
Smart phone emulators currently are not supported

**Comment by enoleriand-alt** [comment]
and yesterday I tried your project and everything was successful and after I reinstalled there were many errors in the package.

**Comment by adnane-X-tebbaa** [comment]
what OS you tried yesterday

**Comment by enoleriand-alt** [comment]
userland

**Comment by enoleriand-alt** [comment]
saya setuju di apk userland yang menyediakan OS linux

**Comment by enoleriand-alt** [comment]
I agree on the UserLand apk that provides Linux OS

**Comment by adnane-X-tebbaa** [comment]
proyek tidak diuji pada userland atau termux tetapi mencoba mengikuti proses instalasi lagi

**Comment by adnane-X-tebbaa** [comment]
the project was not tested on userland or termux but try to follow the installation process again

**Comment by enoleriand-alt** [comment]
I tried it on userland and it worked hmmm and now I am trying to improve your project 😂

**Comment by enoleriand-alt** [comment]
can we talk on wa

**Comment by adnane-X-tebbaa** [comment]
any suggestions to improve the project

**Comment by enoleriand-alt** [comment]
yeah

**Comment by adnane-X-tebbaa** [comment]
any suggestions to improve the project

**Comment by enoleriand-alt** [comment]
![Screenshot_20200409-111422_UserLAnd](https://user-images.githubusercontent.com/59614781/78850906-5c70ec00-7a53-11ea-9ae8-c256a7ec7db0.jpg)

**Comment by adnane-X-tebbaa** [comment]
well i think that i should add "userland" to the supported os list

**Comment by enoleriand-alt** [comment]
![IMG-20200409-WA0073](https://user-images.githubusercontent.com/59614781/78851076-d99c6100-7a53-11ea-97de-c670aa8d6d9e.jpg)

**Comment by adnane-X-tebbaa** [comment]
even TOR supported awesome

**Comment by enoleriand-alt** [comment]
yes 😂 your project is good. and can i push to make you in my repository

**Comment by adnane-X-tebbaa** [comment]
yeah of course

**Comment by enoleriand-alt** [comment]
tq brother 😁

**Comment by adnane-X-tebbaa** [comment]
thank you and dont forget to star if you like the project 
Happy Hunting
